# Generated by Django 5.2.17 on 2026-09-02 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_telemetry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('reading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.telemetry')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalies', to='api.station')),
            ],
        ),
    ]
