# Generated by Django 6.1 on 2026-09-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_station_maintainer_1_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='station',
            name='maintainer_1_phone',
        ),
        migrations.RemoveField(
            model_name='station',
            name='maintainer_2_phone',
        ),
        migrations.RemoveField(
            model_name='station',
            name='maintainer_3_phone',
        ),
        migrations.AddField(
            model_name='station',
            name='maintainer_1_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='maintainer_2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='maintainer_3_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
